fix: file tree does not refresh automatically
phcode-dev/phoenix pull request #1566
Opened 2024-04-25 04:02 UTC by ayoung5555

Bugfix - fixes issue #310 

I ran into the above issue a few weeks ago...

The current behavior is that Phoenix Code will not check for changes made on the local filesystem if that's where the project is being stored. Although there are checks to ensure that opened files are not out of sync, the `ProjectManager` module does not consistently check for new files in the local directory. 

Since changes on the local filesystem (like the example cited in #310 where a file is created via the terminal) typically occur while the user is not in the Phoenix Code window, we can check the local filesystem for changes when the user returns to the window. 

I added a call to `refreshFileTree()` when Phoenix Code comes back into focus, which has resolved the issue.

### Gifs of the change
![phoenix-filesync-demo](https://github.com/phcode-dev/phoenix/assets/40146280/bc69592c-3de7-41a8-a5e0-d2329816c338)

### Does this PR introduce a breaking change?
- No

### Tests done
Tested on Windows and macOS with Chrome and Edge. Does not cause any unit tests to fail.

2024-04-25 04:55 UTC, phoenixide commented
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
ayoung5555
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

2024-04-25 05:13 UTC, abose commented
@ayoung5555 Thank you for contributing to phcode. 

This issue has been bugging me for quite a while as the browser doesn't support external file change watch API for native folders. But this fix addresses that missing API issue quite elegantly without much performance penalty of the background polling logic alternative i thought of( and didn't implement due to its performance penalty). Cool Fix!

Can you sign The CLA  , Also ignore the <firefox mac test failures>, that tends to fail in actions but passes locally with a couple of retries.

2024-04-25 05:16 UTC, abose requested changes

2024-04-25 05:16 UTC, abose commented on src/brackets.js
> +            ProjectManager.refreshFileTree();
Can you make this change too. 
```js
if(!Phoenix.browser.isTauri) { // dont do this in desktop builds as native fs watchers will take care of external changes
  ProjectManager.refreshFileTree();
}
```

2024-04-25 15:52 UTC, ayoung5555 commented on src/brackets.js
> +            ProjectManager.refreshFileTree();
Yup, just added it!

2024-04-25 15:53 UTC, ayoung5555 commented
Thanks! I made the additional fix and submitted a PR to sign the CLA.

2024-04-26 05:27 UTC, phoenixide commented
## Thank You for making this pull request.

2024-04-26 12:31 UTC, merged

2024-04-29 15:35 UTC, abose commented
@ayoung5555 @faizanbhagat The release is now live, about box Release credits has been updated. Thanks for contributing!

![image](https://github.com/phcode-dev/phoenix/assets/5336369/b25b93ce-d78f-4f6c-a026-ee18e7759ee8)